export const ROUTES = {
  HOME: '/',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  FORGOT_PASSWORD: '/auth/forgot-password',
  PRODUCT: (id: number | string) => `/product/${id}`,
  CART: '/cart',
  PROFILE: '/profile',
  GARAGE: '/profile/garage',
  CONTACTS: '/contacts',
  SEARCH: '/search',
  BRANDS: '/brands',
  BRANDS_MODELS: '/brands/models',
  BRAND_MODEL_MODS: '/brands/model',
  BRAND_MODEL_GROUPS: '/brands/model/groups',
  BRAND_MODEL_PARTS: '/brands/model/groups/parts',
  ADMIN: '/admin',
  ADMIN_USERS: '/admin/users',
  ADMIN_SETTINGS: '/admin/settings',
  ADD_CAR: '/add/car',
  ADD_PART: '/add/part',
  ADD_PART_VERIFY: '/add/part/verify',
  ADMIN_VERIFICATIONS: '/admin/verifications',
  ADMIN_LEGAL_ENTITIES: '/admin/legal-entities',
  ABOUT: '/about',
  DELIVERY_TERMS: '/delivery',
  PARTNERS: '/partners',
  NOTIFICATIONS: '/notifications',
} as const;
